spring:
  application:
    name: notification-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: ${SERVER_PORT:8087}

app:
  kafka:
    topic:
      appointment-booked: appointment-booked
      order-placed: order-placed
      lab-report-uploaded: lab-report-uploaded
      emergency-triggered: emergency-triggered
  scheduler:
    medicine-reminder-cron: "0 0 8,14,20 * * *"

spring.kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}

management:
  endpoints:
    web:
      exposure:
        include: health,info
