spring:
  application:
    name: pharmacy-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/mediconnect_pharmacy?useSSL=false&serverTimezone=UTC}
    username: ${DB_USER:mediconnect}
    password: ${DB_PASSWORD:mediconnect}

server:
  port: ${SERVER_PORT:8085}

app:
  kafka:
    topic:
      prescription-created: prescription-created
      order-placed: order-placed

spring.kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}

management:
  endpoints:
    web:
      exposure:
        include: health,info
